name: "Comprueba los proyectos por hito"
on:
  pull_request:
    paths:
      - 'proyectos/[1234567].md'

jobs:
  extrae_usuario_repo:
    runs-on: ubuntu-latest
    outputs:
      user: ${{steps.user_repo.outputs.user}}
      repo: ${{steps.user_repo.outputs.repo}}
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Extrae usuario y nombre del repo
        uses: actions/github-script@v3
        id: user_repo
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Encontrado repo " + repo + " para usuario " + user )
                console.log( "::set-output name=user::" + user )
                console.log( "::set-output name=repo::" + repo )
            }
  comprueba_hito_1:
    runs-on: ubuntu-latest
    needs: extrae_usuario_repo
    env:
      CC_USER: ${{ needs.extrae_usuario_repo.outputs.user }}
      CC_REPO: ${{ needs.extrae_usuario_repo.outputs.repo }}
    steps:
      - name: Comprueba hitos en repo estudiante
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const user = process.env.CC_USER
              const repo = process.env.CC_REPO
              console.log( "» Trabajando con el repo " + repo + " para el usuario " + user )
              const milestones = await github.issues.listMilestones( { owner: user, repo: repo } )
              if ( ! milestones.data.length ) {
                  core.setFailed("❌ Tiene que haber por lo menos un milestone")
              }
              const minMilestones = 3
              if ( minMilestones && milestones.data.length < minMilestones ) {
                  core.setFailed( "❌ Tendría que haber más de " + minMilestones + " milestone(s)");
              }
              var totalIssues = 0
              var totalClosedIssues = 0
              milestones.data.forEach( async function( milestone ) {
                  totalIssues += milestone.open_issues + milestone.closed_issues
                  totalClosedIssues += milestone.closed_issues
              })
              console.log( "✅ Hay " + totalIssues + " issues en tus milestones y " + totalClosedIssues + " cerrados ")
              if ( ! totalIssues ) {
                  core.setFailed( "❌ No hay ningún issue en tus milestones")
              } else if ( ! totalClosedIssues ) {
                  core.setFailed( "❌ No hay ningún issue cerrado milestones")
              }

      - name: Busca historias de usuario e issues cerrados
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const user = process.env.CC_USER
            const repo = process.env.CC_REPO
            console.log( "» Analizando repo " + repo + " del usuario 🔥" + user )
            const non_paginated_issues = await github.issues.listForRepo.endpoint.merge( { owner: user, repo: repo })
            const issues = await github.paginate( non_paginated_issues )
            const user_stories = issues.filter( issue => issue.labels.filter( label => label.name === "user-stories" ).length > 0 && ( issue.title.includes('HU') || issue.title.includes('US') ) && issue.milestone )
            if ( user_stories.length > 0 ) {
              console.log( " ✅ Hay al menos una historia de usuario " )
            } else {
              core.setFailed( " ❌ No hay ninguna historia de usuario en el repo " )
            }

            const closed_issues = issues.filter( issue => issue.state === "closed" )
            closed_issues.forEach( async function( issue ) {
              if ( ! issue.pull_request ) {
                        const query = `query($owner:String!, $name:String!, $issue:Int!) {
                            repository(name: $name , owner: $owner  ) {
                              issue(number: $issue) {
                                timelineItems(itemTypes: CLOSED_EVENT, last: 1) {
                                  nodes {
                                    ... on ClosedEvent {
                                      closer {
                                        __typename
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }`;

                const variables = {
                          owner: user,
                          name: repo,
                          issue: issue.number
                          }
                const result = await github.graphql(query, variables)
                if ( result.repository.issue.timelineItems.nodes[0].closer != null ) {
                            const closingEvent = result.repository.issue.timelineItems.nodes[0].closer.__typename
                            if ( (closingEvent == 'Commit') || (closingEvent == 'PullRequest') ) {
                                console.log(" ✅ El issue " + issue.number + " se cerró con un " + closingEvent )
                            } else {
                                core.setFailed( "❌ El issue " + issue.number + " no se cerró con un commit o PR")
                            }
                } else {
                  console.log( "❌ El issue " + issue.number + " no está cerrado aunque aparece en la lista de tales " )
                }
              }
            })
  ops_on_repo:
    runs-on: ubuntu-latest
    needs: extrae_usuario_repo
    outputs:
      container: ${{steps.container.outputs.CONTAINER}}
      orden_tareas: ${{steps.container.outputs.CC_ORDEN_TAREAS}}
    env:
      CC_USER: ${{ needs.extrae_usuario_repo.outputs.user }}
      CC_REPO: ${{ needs.extrae_usuario_repo.outputs.repo }}
    steps:
      - name: Descarga repo usuario y decodifica configuración
        uses: actions/checkout@v2
        with:
          repository: '${{env.CC_USER}}/${{env.CC_REPO}}'
      - name: Descarga ysh y ejecuta
        id: container
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
          ysh -v
          # Estamos en el repo del estudiante
          curl https://raw.githubusercontent.com/JJ/CC-20-21/master/.github/workflows/procesa_yaml.sh --output procesa_yaml.sh
          chmod +x ./procesa_yaml.sh
          ./procesa_yaml.sh
          if test -f "DOCKER_USER"; then
            echo "❢ Usuario de Docker alternativo"
            CC_USER=`cat DOCKER_USER`
          fi
          echo "::set-output name=CONTAINER::${CC_USER}/${CC_REPO}"
          echo "CONTAINER=${CC_USER}/${CC_REPO}" >> $GITHUB_ENV
      - name: Filtra hito
        uses: dorny/paths-filter@v2
        id: hito3
        with:
          filters: |
            src:
              - 'proyectos/[345678].md'
      - name: Testea el contenedor
        if: steps.hito3.outputs.src == 'true'
        run: docker run -t -v `pwd`:/app/test ${CONTAINER,,}
      - name: Testea microservicio hito 5
        uses: dorny/paths-filter@v2
        id: hito5
        with:
          filters: |
            src:
              - 'proyectos/[567].md'
      - name: Ejecuta test del microservicio
        if: steps.hito5.outputs.src == 'true'
        run: |
          docker run -t -v `pwd`:/app/test ${CONTAINER,,} sh -c "ls && ${CC_ORDEN_TAREAS} build && ${CC_ORDEN_TAREAS} install && ${CC_ORDEN_TAREAS} test"

  test-ci-status:
    runs-on: ubuntu-latest
    needs: extrae_usuario_repo
    env:
      CC_USER: ${{ needs.extrae_usuario_repo.outputs.user }}
      CC_REPO: ${{ needs.extrae_usuario_repo.outputs.repo }}
    steps:
      - name: Filtra hito
        uses: dorny/paths-filter@v2
        id: hito4
        with:
          filters: |
            src:
              - 'proyectos/[45678].md'
      - name: Comprueba el estado de CI
        if: steps.hito4.outputs.src == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const user = process.env.CC_USER // segundo resultado
            const repo = process.env.CC_REPO // tercer resultado
            console.log( "» Analizando repo " + repo + " del usuario 🔥" + user )
            const checks_before_pag =
                    await github.checks.listForRef.endpoint.merge(
                        { owner: user,
                          repo: repo,
                          ref: 'HEAD',
                          status: 'completed'
                        })
            const checks = await github.paginate( checks_before_pag)
            console.log( "✅ Hay " + checks.length + " sistemas de CI configurados")

            if ( checks.length < 1 ) {
                    core.setFailed("❌ No hay suficientes sistemas de CI configurados")
            }
            const green_checks = checks.filter( check => check.conclusion === "success" )
            if ( !green_checks.length ) {
              core.setFailed("❌ No hay al menos un CI que esté en verde")
            } else {
              console.log( "✅ Hay " + green_checks.length + " que pasa(n) los tests correctamente" )
            }
            const travis_checks_green = green_checks.filter( check => check.app.slug === "travis-ci" )

            if ( travis_checks_green.length == 0 ) {
              const circle_checks_green = green_checks.filter( check => check.app.slug === "circle-ci" )
              if ( circle_checks_green.length == 0 ) {
                core.setFailed("❌ Travis y Circle no están o está fallando en este momento")
              }
            } else {
              console.log( "✅ Entre ellos está Travis" )
            }
